// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujaauksjrbyjdzethult.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqYWF1a3NqcmJ5amR6ZXRodWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzM4MTUsImV4cCI6MjA3NDIwOTgxNX0.0TB4K4gg3v4_O9kW6X3A3mvtUSTEm83FCvwI9ds-sF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});